package sqlite

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
	"database/sql"
)

// OauthToken represents a row from 'oauth_tokens'.
type OauthToken struct {
	ID                       int            `json:"id"`                          // id
	App                      string         `json:"app"`                         // app
	Type                     string         `json:"type"`                        // type
	ClientID                 string         `json:"client_id"`                   // client_id
	ClientSecret             string         `json:"client_secret"`               // client_secret
	OriginalRefreshToken     string         `json:"original_refresh_token"`      // original_refresh_token
	RefreshToken             string         `json:"refresh_token"`               // refresh_token
	AccessToken              string         `json:"access_token"`                // access_token
	ExpiresAt                *Time          `json:"expires_at"`                  // expires_at
	CreatedAt                Time           `json:"created_at"`                  // created_at
	UpdatedAt                Time           `json:"updated_at"`                  // updated_at
	CodeExchangeResponseBody sql.NullString `json:"code_exchange_response_body"` // code_exchange_response_body
	CodeVerifier             string         `json:"code_verifier"`               // code_verifier
	RefreshTokenExpiresAt    *Time          `json:"refresh_token_expires_at"`    // refresh_token_expires_at
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [OauthToken] exists in the database.
func (ot *OauthToken) Exists() bool {
	return ot._exists
}

// Deleted returns true when the [OauthToken] has been marked for deletion
// from the database.
func (ot *OauthToken) Deleted() bool {
	return ot._deleted
}

// Insert inserts the [OauthToken] to the database.
func (ot *OauthToken) Insert(ctx context.Context, db DB) error {
	switch {
	case ot._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case ot._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO oauth_tokens (` +
		`app, type, client_id, client_secret, original_refresh_token, refresh_token, access_token, expires_at, created_at, updated_at, code_exchange_response_body, code_verifier` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12` +
		`)`
	// run
	logf(sqlstr, ot.App, ot.Type, ot.ClientID, ot.ClientSecret, ot.OriginalRefreshToken, ot.RefreshToken, ot.AccessToken, ot.ExpiresAt, ot.CreatedAt, ot.UpdatedAt, ot.CodeExchangeResponseBody, ot.CodeVerifier)
	res, err := db.ExecContext(ctx, sqlstr, ot.App, ot.Type, ot.ClientID, ot.ClientSecret, ot.OriginalRefreshToken, ot.RefreshToken, ot.AccessToken, ot.ExpiresAt, ot.CreatedAt, ot.UpdatedAt, ot.CodeExchangeResponseBody, ot.CodeVerifier)
	if err != nil {
		return logerror(err)
	}
	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return logerror(err)
	} // set primary key
	ot.ID = int(id)
	// set exists
	ot._exists = true
	return nil
}

// Update updates a [OauthToken] in the database.
func (ot *OauthToken) Update(ctx context.Context, db DB) error {
	switch {
	case !ot._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case ot._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with primary key
	const sqlstr = `UPDATE oauth_tokens SET ` +
		`app = $1, type = $2, client_id = $3, client_secret = $4, original_refresh_token = $5, refresh_token = $6, access_token = $7, expires_at = $8, created_at = $9, updated_at = $10, code_exchange_response_body = $11, code_verifier = $12, refresh_token_expires_at = $13 ` +
		`WHERE id = $14`
	// run
	logf(sqlstr, ot.App, ot.Type, ot.ClientID, ot.ClientSecret, ot.OriginalRefreshToken, ot.RefreshToken, ot.AccessToken, ot.ExpiresAt, ot.CreatedAt, ot.UpdatedAt, ot.CodeExchangeResponseBody, ot.CodeVerifier, ot.RefreshTokenExpiresAt, ot.ID)
	if _, err := db.ExecContext(ctx, sqlstr, ot.App, ot.Type, ot.ClientID, ot.ClientSecret, ot.OriginalRefreshToken, ot.RefreshToken, ot.AccessToken, ot.ExpiresAt, ot.CreatedAt, ot.UpdatedAt, ot.CodeExchangeResponseBody, ot.CodeVerifier, ot.RefreshTokenExpiresAt, ot.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [OauthToken] to the database.
func (ot *OauthToken) Save(ctx context.Context, db DB) error {
	if ot.Exists() {
		return ot.Update(ctx, db)
	}
	return ot.Insert(ctx, db)
}

// Upsert performs an upsert for [OauthToken].
func (ot *OauthToken) Upsert(ctx context.Context, db DB) error {
	switch {
	case ot._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO oauth_tokens (` +
		`id, app, type, client_id, client_secret, original_refresh_token, refresh_token, access_token, expires_at, created_at, updated_at, code_exchange_response_body, code_verifier, refresh_token_expires_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`app = EXCLUDED.app, type = EXCLUDED.type, client_id = EXCLUDED.client_id, client_secret = EXCLUDED.client_secret, original_refresh_token = EXCLUDED.original_refresh_token, refresh_token = EXCLUDED.refresh_token, access_token = EXCLUDED.access_token, expires_at = EXCLUDED.expires_at, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, code_exchange_response_body = EXCLUDED.code_exchange_response_body, code_verifier = EXCLUDED.code_verifier, refresh_token_expires_at = EXCLUDED.refresh_token_expires_at`
	// run
	logf(sqlstr, ot.ID, ot.App, ot.Type, ot.ClientID, ot.ClientSecret, ot.OriginalRefreshToken, ot.RefreshToken, ot.AccessToken, ot.ExpiresAt, ot.CreatedAt, ot.UpdatedAt, ot.CodeExchangeResponseBody, ot.CodeVerifier, ot.RefreshTokenExpiresAt)
	if _, err := db.ExecContext(ctx, sqlstr, ot.ID, ot.App, ot.Type, ot.ClientID, ot.ClientSecret, ot.OriginalRefreshToken, ot.RefreshToken, ot.AccessToken, ot.ExpiresAt, ot.CreatedAt, ot.UpdatedAt, ot.CodeExchangeResponseBody, ot.CodeVerifier, ot.RefreshTokenExpiresAt); err != nil {
		return logerror(err)
	}
	// set exists
	ot._exists = true
	return nil
}

// Delete deletes the [OauthToken] from the database.
func (ot *OauthToken) Delete(ctx context.Context, db DB) error {
	switch {
	case !ot._exists: // doesn't exist
		return nil
	case ot._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM oauth_tokens ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, ot.ID)
	if _, err := db.ExecContext(ctx, sqlstr, ot.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	ot._deleted = true
	return nil
}

// OauthTokenByID retrieves a row from 'oauth_tokens' as a [OauthToken].
//
// Generated from index 'oauth_tokens_id_pkey'.
func OauthTokenByID(ctx context.Context, db DB, id int) (*OauthToken, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, app, type, client_id, client_secret, original_refresh_token, refresh_token, access_token, expires_at, created_at, updated_at, code_exchange_response_body, code_verifier, refresh_token_expires_at ` +
		`FROM oauth_tokens ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	ot := OauthToken{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&ot.ID, &ot.App, &ot.Type, &ot.ClientID, &ot.ClientSecret, &ot.OriginalRefreshToken, &ot.RefreshToken, &ot.AccessToken, &ot.ExpiresAt, &ot.CreatedAt, &ot.UpdatedAt, &ot.CodeExchangeResponseBody, &ot.CodeVerifier, &ot.RefreshTokenExpiresAt); err != nil {
		return nil, logerror(err)
	}
	return &ot, nil
}

// OauthTokensByAppAccessToken retrieves a row from 'oauth_tokens' as a [OauthToken].
//
// Generated from index 'ot_app_access_token'.
func OauthTokensByAppAccessToken(ctx context.Context, db DB, app, accessToken string) ([]*OauthToken, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, app, type, client_id, client_secret, original_refresh_token, refresh_token, access_token, expires_at, created_at, updated_at, code_exchange_response_body, code_verifier, refresh_token_expires_at ` +
		`FROM oauth_tokens ` +
		`WHERE app = $1 AND access_token = $2 AND (refresh_token_expires_at IS NULL OR refresh_token_expires_at > $3)`
	// run
	refreshTokenExpiresAt := NewTime(time.Now())
	logf(sqlstr, app, accessToken, refreshTokenExpiresAt)
	rows, err := db.QueryContext(ctx, sqlstr, app, accessToken, refreshTokenExpiresAt)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*OauthToken
	for rows.Next() {
		ot := OauthToken{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&ot.ID, &ot.App, &ot.Type, &ot.ClientID, &ot.ClientSecret, &ot.OriginalRefreshToken, &ot.RefreshToken, &ot.AccessToken, &ot.ExpiresAt, &ot.CreatedAt, &ot.UpdatedAt, &ot.CodeExchangeResponseBody, &ot.CodeVerifier, &ot.RefreshTokenExpiresAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &ot)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// OauthTokenByAppClientIDClientSecretOriginalRefreshToken retrieves a row from 'oauth_tokens' as a [OauthToken].
//
// Generated from index 'ot_app_client_id_client_secret_original_refresh_token'.
func OauthTokenByAppClientIDClientSecretOriginalRefreshToken(ctx context.Context, db DB, app, clientID, clientSecret, originalRefreshToken string) (*OauthToken, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, app, type, client_id, client_secret, original_refresh_token, refresh_token, access_token, expires_at, created_at, updated_at, code_exchange_response_body, code_verifier, refresh_token_expires_at ` +
		`FROM oauth_tokens ` +
		`WHERE app = $1 AND client_id = $2 AND client_secret = $3 AND original_refresh_token = $4 AND (refresh_token_expires_at IS NULL OR refresh_token_expires_at > $4)`
	// run
	refreshTokenExpiresAt := NewTime(time.Now())
	logf(sqlstr, app, clientID, clientSecret, originalRefreshToken, originalRefreshToken, refreshTokenExpiresAt)
	ot := OauthToken{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, app, clientID, clientSecret, originalRefreshToken, refreshTokenExpiresAt).Scan(&ot.ID, &ot.App, &ot.Type, &ot.ClientID, &ot.ClientSecret, &ot.OriginalRefreshToken, &ot.RefreshToken, &ot.AccessToken, &ot.ExpiresAt, &ot.CreatedAt, &ot.UpdatedAt, &ot.CodeExchangeResponseBody, &ot.CodeVerifier, &ot.RefreshTokenExpiresAt); err != nil {
		return nil, logerror(err)
	}
	return &ot, nil
}

// OauthTokenByAppClientIDClientSecretRefreshToken retrieves a row from 'oauth_tokens' as a [OauthToken].
//
// Generated from index 'ot_app_client_id_client_secret_refresh_token'.
func OauthTokenByAppClientIDClientSecretRefreshToken(ctx context.Context, db DB, app, clientID, clientSecret, refreshToken string) (*OauthToken, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, app, type, client_id, client_secret, original_refresh_token, refresh_token, access_token, expires_at, created_at, updated_at, code_exchange_response_body, code_verifier, refresh_token_expires_at ` +
		`FROM oauth_tokens ` +
		`WHERE app = $1 AND client_id = $2 AND client_secret = $3 AND refresh_token = $4 AND (refresh_token_expires_at IS NULL OR refresh_token_expires_at > $5)`
	// run
	refreshTokenExpiresAt := NewTime(time.Now())
	logf(sqlstr, app, clientID, clientSecret, refreshToken, refreshTokenExpiresAt)
	ot := OauthToken{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, app, clientID, clientSecret, refreshToken, refreshTokenExpiresAt).Scan(&ot.ID, &ot.App, &ot.Type, &ot.ClientID, &ot.ClientSecret, &ot.OriginalRefreshToken, &ot.RefreshToken, &ot.AccessToken, &ot.ExpiresAt, &ot.CreatedAt, &ot.UpdatedAt, &ot.CodeExchangeResponseBody, &ot.CodeVerifier, &ot.RefreshTokenExpiresAt); err != nil {
		return nil, logerror(err)
	}
	return &ot, nil
}

// OauthTokensByAppOriginalRefreshToken retrieves a row from 'oauth_tokens' as a [OauthToken].
//
// Generated from index 'ot_app_original_refresh_token'.
func OauthTokensByAppOriginalRefreshToken(ctx context.Context, db DB, app, originalRefreshToken string) ([]*OauthToken, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, app, type, client_id, client_secret, original_refresh_token, refresh_token, access_token, expires_at, created_at, updated_at, code_exchange_response_body, code_verifier, refresh_token_expires_at ` +
		`FROM oauth_tokens ` +
		`WHERE app = $1 AND original_refresh_token = $2 AND (refresh_token_expires_at IS NULL OR refresh_token_expires_at > $3)`
	// run
	refreshTokenExpiresAt := NewTime(time.Now())
	logf(sqlstr, app, originalRefreshToken, refreshTokenExpiresAt)
	rows, err := db.QueryContext(ctx, sqlstr, app, originalRefreshToken, refreshTokenExpiresAt)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*OauthToken
	for rows.Next() {
		ot := OauthToken{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&ot.ID, &ot.App, &ot.Type, &ot.ClientID, &ot.ClientSecret, &ot.OriginalRefreshToken, &ot.RefreshToken, &ot.AccessToken, &ot.ExpiresAt, &ot.CreatedAt, &ot.UpdatedAt, &ot.CodeExchangeResponseBody, &ot.CodeVerifier, &ot.RefreshTokenExpiresAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &ot)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// OauthTokenByAppRefreshToken retrieves a row from 'oauth_tokens' as a [OauthToken].
//
// Generated from index 'ot_app_refresh_token'.
func OauthTokenByAppRefreshToken(ctx context.Context, db DB, app, refreshToken string) (*OauthToken, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, app, type, client_id, client_secret, original_refresh_token, refresh_token, access_token, expires_at, created_at, updated_at, code_exchange_response_body, code_verifier, refresh_token_expires_at ` +
		`FROM oauth_tokens ` +
		`WHERE app = $1 AND refresh_token = $2 AND (refresh_token_expires_at IS NULL OR refresh_token_expires_at > $3)`
	// run
	refreshTokenExpiresAt := NewTime(time.Now())
	logf(sqlstr, app, refreshToken, refreshTokenExpiresAt)
	ot := OauthToken{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, app, refreshToken, refreshTokenExpiresAt).Scan(&ot.ID, &ot.App, &ot.Type, &ot.ClientID, &ot.ClientSecret, &ot.OriginalRefreshToken, &ot.RefreshToken, &ot.AccessToken, &ot.ExpiresAt, &ot.CreatedAt, &ot.UpdatedAt, &ot.CodeExchangeResponseBody, &ot.CodeVerifier, &ot.RefreshTokenExpiresAt); err != nil {
		return nil, logerror(err)
	}
	return &ot, nil
}
